### ISSUE TITLE
A recent upgrade to `gridExtra` broke the package

### ISSUE THREAD

**Issue by briandk** [briandk/granovaGG#166]
A few days ago `granovaGG` started failing CRAN package checks, and a CRAN maintainer notified me. 

Baptiste Auguie on 2016-02-28 wrote:

> Most of the warnings appear due to a conflict between plyr::join and gridExtra::join. **Packages listing gridExtra in Imports: should probably be selective in what they import (with importFrom directives in the NAMESPACE file)**, and that would solve the problem. For those few packages that list gridExtra in Depends: I'm not sure what to suggest other than moving either plyr or gridExtra to Imports: and be selective (this advice has been a recurring theme lately, to alleviate such name masking). 
> 
> Since gridExtra::join is not a particularly apt name in the first place, I'll also consider renaming it, but selective imports are still useful regardless. (emphasis mine)

**Comment by briandk** [comment]
So I tweeted: https://twitter.com/Capbri/status/704345883102617600

**Comment by briandk** [comment]
In short, Baptiste is recommending an `@importFrom` solution while @hadley advises against it:

<img width="869" alt="2016-02-29 - using importfrom in r packages 02-29-16 11 55 58 am" src="https://cloud.githubusercontent.com/assets/330036/13401750/670b1180-dedb-11e5-9321-d3766672161d.png">

Source: https://cran.r-project.org/web/packages/roxygen2/vignettes/namespace.html

**Comment by jennybc** [comment]
Sounds like this is a good excuse to move towards, e.g., `gridExtra::join()`, instead of importing the entire namespace of `gridExtra` and calling `join()`. I don't find any uses of `join()` in this repo, so the conflict/masking must be coming from some other function. But that's really neither here nor there -- the `pkg::foo()` approach is a general practice people are adopting to eliminate these headaches. So it might also apply to `reshape2` and `plyr` here, in addition to `gridExtra`.

**Comment by briandk** [comment]
@jennybc Thank you so much! This is wonderful advice. I think I've found a problematic edge case though, where I don't know what to do:

What happens when you only want to reference one function from a package, but that function references *another* function from a package. It seems like using double-colon notation doesn't work. In my case, I think I'm having a problem where `gridExtar::grid.arrange()` internally calls `gridExtra::arrangeGrob()`, and I don't know how to make sure that internal call works.

Here's an abstracted minimal example.

## A minimal example of where `foo::bar()` notation gets tricky

Suppose your package depends on package `foo`, and you only use one function: `foo::bar()`. But, **also** suppose that the definition of `foo::bar()` depends on another function `baz()` in that package: `foo::baz()`. 

So what you do is 

- put `foo` in your `DESCRIPTION`'s `Imports:` field, 
- Do NOT use `@import foo` in any roxygen blocks
- Call `foo::bar()` within your package as needed.

### the definition of `foo::bar()` looks like this:

```r
# @export
bar <- function(x) {
  return(baz(x))

}
```

### `foo`'s DESCRIPTION collate file looks like this:

```yaml
Collate:
    'baz.R',
    'bar.R'
```

### The Million Dollar Question

When your code calls `foo::bar()`, will it succeed?

/cc @WilDoane

**Comment by WilDoane** [comment]
It should work. Consider the (somewhat messy) case:

    gg1 <- ggplot2::ggplot(mtcars) + ggplot2::geom_histogram(ggplot2::aes(x = hp))
    gg2 <- ggplot2::ggplot(mtcars) + ggplot2::geom_histogram(ggplot2::aes(x = mpg))
    
    gridExtra::grid.arrange(gg1, gg2)

when ggplot2 and gridExtra packages are not attached. it works fine and plots the result.

**Comment by jennybc** [comment]
As @WilDoane says, it will work. Do you feel like you're seeing something else? I mean, almost all functions in a package will call other exported and unexpected functions in that package, so this is not an uncommon situation.

To learn perhaps more than you wanted to know about this, I recommend:

http://blog.obeautifulcode.com/R/How-R-Searches-And-Finds-Stuff/
